docker_repo_arch: "{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}"
docker_repo_flavor: "{{ 'debian' if (ansible_distribution | lower) in ['debian', 'raspbian'] else 'ubuntu' }}"
