nomad_datacenter: home
nomad_server: false
nomad_client: true
nomad_server_bootstrap_expect: 1
nomad_retry_join: []
nomad_node_name: "{{ inventory_hostname }}"
nomad_node_class: ""

nomad_host_volumes: []

nomad_cni_paths: "/opt/cni/bin:/usr/lib/cni:/usr/libexec/cni"
nomad_cni_config_dir: "/etc/cni/net.d"

nomad_repo_arch: "{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}"
