consul_server: false
consul_bootstrap_expect: 1
consul_retry_join: []
consul_node_name: "{{ inventory_hostname }}"
consul_datacenter: home
consul_repo_arch: "{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}"
consul_ui_enable: true
